### ISSUE TITLE
Incorrect “Website Already Saved” notification

### ISSUE THREAD

**Issue by akshath90** [DataXResearch/rabbithole#18]
Saved website not linked to specific project, instead it is linked to a database of all websites saved. Incorrectly says “Website Already Saved” if it is saved twice, each time to a different project

**Comment by govi218** [comment]
This should be fixed in #13, can you confirm?

**Comment by akshath90** [comment]
Nope, still an issue. Once URL is saved, it still shows "Website already saved" despite choosing a new project.
